name: DynamicShop
version: ${project.version}
main: me.sat7.dynamicshop.DynamicShop
depend: [Vault]
softdepend: [PlaceholderAPI, Jobs]
api-version: 1.13
authors: [sat7, Multitallented]
description: Full GUI shop with dynamic prices
commands:
  DynamicShop:
    description: "Full GUI shop with dynamic prices"
    aliases: [ds]
  shop:
permissions:
  dshop.use:
    description: Allows use of the /ds command
    default: true
  dshop.use.qsell:
    description: Allows use of the /ds qsell command
    default: true